### ISSUE TITLE
Option to disable command feedback

### ISSUE THREAD

**Issue by Dagrond** [iGabyTM/MasterCooldowns#6]
So I'm using MasterCooldowns quite a lot in my GUI menus etc for cooldowns. But everytime an cooldown is added, the console is spammed with 'a new cooldown has been added' messages. I don't need those, there should be option to disable command feedback when running from console or by adding '-s' argument to the command.

**Comment by iGabyTM** [comment]
https://github.com/iGabyTM/mastercooldowns/blob/fcab1aebcefaca12873f0e8b7c43f045728ec595/src/main/resources/config.yml#L32-L33
Setting these two booleans to false will remove the messages.

**Comment by Dagrond** [comment]
> https://github.com/iGabyTM/mastercooldowns/blob/fcab1aebcefaca12873f0e8b7c43f045728ec595/src/main/resources/config.yml#L32-L33
> 
> 
> Setting these two booleans to false will remove the messages.

This is only applicable when setting cooldown of ALL players I believe? I want not to send feedback messages even if the cooldown was created only for one player. If there is 50+ online players, these messages can spam server console quite a bit.

**Comment by iGabyTM** [comment]
I see, I see. I will add an option for this too
